version: '3.8'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: always
    ports:
      - "54:53/udp"
      - "54:53/tcp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - ./etc/bind:/etc/bind
      - ./var/cache/bind:/var/cache/bind
